Ej/port navigation
digidem/react-native-with-mapeo-core-next pull request #30
Opened 2023-08-23 13:19 UTC by lightlii

Installs and configures react-navigation and creates basic setup with navigator + custom header

closes https://github.com/digidem/react-native-with-mapeo-core-next/issues/12

2023-08-23 16:20 UTC, lightlii commented
I've attempted porting over the flow typing in [src/frontend/types/index.ts](https://github.com/digidem/react-native-with-mapeo-core-next/pull/30/files#diff-0dc7ba143a2d6c2b0d35f6c810c111a56f2fd78a422a45f52f6ce1f6af8b7443) as well as the [declarations for react-navigation](https://github.com/digidem/react-native-with-mapeo-core-next/pull/30/files#diff-5ef0552e05e1f80cbec5be4233c83ccbd9650ad6b06c0c33188a2874a0f91c77) but I still get the error `Cannot find module 'react-navigation' or its corresponding type declarations.` ...Not sure I've well understood how this is working

2023-08-23 16:43 UTC, ErikSin commented
> I've attempted porting over the flow typing in [src/frontend/types/index.ts](https://github.com/digidem/react-native-with-mapeo-core-next/pull/30/files#diff-0dc7ba143a2d6c2b0d35f6c810c111a56f2fd78a422a45f52f6ce1f6af8b7443) as well as the [declarations for react-navigation](https://github.com/digidem/react-native-with-mapeo-core-next/pull/30/files#diff-5ef0552e05e1f80cbec5be4233c83ccbd9650ad6b06c0c33188a2874a0f91c77) but I still get the error `Cannot find module 'react-navigation' or its corresponding type declarations.` ...Not sure I've well understood how this is working

Perhaps i don't fully understand what is going on here, but these look like manual typings of react-nav.  I assumed they were used by flow? We don't need these flow typings anymore, as the TS typing are part of the react-nav library, except for the custom types created in [sharedTypes.ts](https://github.com/digidem/mapeo-mobile/blob/develop/src/frontend/sharedTypes.ts).

2023-08-23 21:36 UTC, ErikSin requested changes
We should bring over the basic <CustomHeaderLeft/>. Take out any code that isnt related to the title and the back button.

Also we should follow the patter of pages (expect for the bottom tab navigator screen) having a `title` property  so that it can be injected into the header eventually

And we should bring over all the [typings](https://github.com/digidem/mapeo-mobile/blob/ca167c257b90ba74b0e63e623f405aed98d86145/src/frontend/sharedTypes.ts#L41).

2023-08-23 21:36 UTC, ErikSin commented on android/app/src/main/java/com/mapeonext/MainActivity.java
what is this for?

2023-08-23 21:36 UTC, ErikSin commented on src/frontend/hooks/useNavigationWithTypes.ts
> +import {AppStackList, HomeTabsList} from '../Navigation/AppStack';
`HomeTabsList` is importing from the wrong place

2023-08-23 21:36 UTC, ErikSin commented on src/frontend/types/index.ts
can be deleted

2023-08-23 21:36 UTC, ErikSin commented on src/frontend/types/react-navigation.d.ts
can be deleted

2023-08-24 12:46 UTC, lightlii commented on android/app/src/main/java/com/mapeonext/MainActivity.java
https://reactnavigation.org/docs/getting-started#installation

2023-08-24 20:30 UTC, ErikSin approved these changes

2023-08-24 20:31 UTC, ErikSin commented
navigation is blocking alot of tickets! So i just added the header and cleaned it up @lightlii

2023-08-24 20:31 UTC, merged